version: "3"
services:
  map-component:
    image: cospirit/node:12.16.2
    container_name: map-component_app
    restart: always
    working_dir: /srv/map-component
    hostname: map
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.map-component.rule=Host(`map-component.cospirit.local`)"
      - "traefik.http.routers.map-component.entrypoints=web"
      - "traefik.http.routers.map-component.service=map-component"
      - "traefik.http.services.intranet-pcm.loadbalancer.server.port=80"
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - ./:/srv/map-component
      - $SSH_AUTH_SOCK:/ssh-agent
    networks:
      - traefik-proxy
    ports:
      - 80

networks:
  traefik-proxy:
    external: true
