version: "3"
services:
  cospirit-map-component:
    image: cospirit/node:12.16.2
    container_name: cospirit-map-component
    restart: always
    working_dir: /srv/cospirit-map-component
    tty: true
    networks:
      - traefik-proxy
    volumes:
      - ./:/srv/cospirit-map-component
      - $SSH_AUTH_SOCK:/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    ports:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.cospirit-map-component.rule=Host(`map-component.cospirit-connect.local`)"
      - "traefik.http.routers.cospirit-map-component.entrypoints=web"
      - "traefik.http.routers.cospirit-map-component.service=cospirit-map-component"
      - "traefik.http.services.cospirit-map-component.loadbalancer.server.port=80"

networks:
  traefik-proxy:
    external: true
