version: "3.8"

services:
  app:
    image: cospirit/node:12.16.2
    container_name: map-component_app
    restart: always
    working_dir: /srv/app
    user: node
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.map-component.rule=Host(`map-component.cospirit.local`)"
      - "traefik.http.routers.map-component.entrypoints=web"
      - "traefik.http.routers.map-component.service=map-component"
      - "traefik.http.services.map-component.loadbalancer.server.port=80"
    volumes:
      - ./:/srv/app
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
