version: "3"
services:
  cospirit-map-component:
    image: cospirit/node:12.16.2
    container_name: cospirit-map-component
    restart: always
    working_dir: /srv/cospirit-map-component
    hostname: map
    tty: true
    networks:
      - public
    volumes:
      - ./:/srv/cospirit-map-component
      - $SSH_AUTH_SOCK:/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    ports:
      - 80
    labels:
      - "traefik.backend=component-cospirit-map"
      - "traefik.frontend.rule=Host:cospirit-map-component.localhost"
      - "traefik.docker.network=public"
networks:
  public:
    external:
      name: public
