version: 2.1

executors:
  node:
    docker:
      - image: cospirit/node:12.16.2

jobs:
  build:
    executor: node
    steps:
      - checkout
      # System installs
      - run:
          name: Versions
          command: |
            echo "******** Node *****" && node -v
            echo "******** Npm **********" && npm -v
      - run: env

      # Download and cache npm dependencies
      - restore_cache:
          keys:
            - v1-npm-packages-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: v1-npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # Build
      - run:
          name: Build
          command: make test@assets.build

  linter:
    executor: node
    steps:
      - checkout
      # Download and cache npm dependencies
      - restore_cache:
          keys:
            - v1-npm-packages-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: v1-npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # Run linter
      - run:
          name: Run linter
          command: make test@lint

workflows:
  version: 2.1

  workflow:
    jobs:
      - build
      - linter
